name: Deploy PR for Testing

on:
  workflow_dispatch
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: terraform/
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::784714698706:role/TEMP-GH-ACTIONS
          role-session-name: deploy-to-aws
          aws-region: us-east-2

      - name: Echo Ref 
        run: echo "$GITHUB_REF"

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Terraform Apply
        id: appply
        run: terraform apply -auto-approve

      - name: Get API URL
        id: api-url
        run: echo "$(terraform output invoke_url)"