name: Deploy PR for Testing

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: terraform/
    outputs:
      invoke_url: ${{steps.set-invoke-url.outputs.inovke_url}}
      s3_domain: ${{steps.set-s3-domain.outputs.s3_domain}}
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::784714698706:role/TEMP-GH-ACTIONS
          role-session-name: deploy-to-aws
          aws-region: us-east-2

      - name: Echo Ref 
        run: echo "$GITHUB_REF"

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Terraform Apply
        id: appply
        run: terraform apply -auto-approve

      - name: Set Invoke URL
        id: set-invoke-url
        run: echo "inovke_url=$(terraform output invoke_url)" >> "$GITHUB_OUTPUT"

      - name: Set Static S3 domain
        id: set-s3-domain
        run: echo "s3_domain=$(terraform output static_s3_domain)" >> "$GITHUB_OUTPUT"

      

  frontend:
    runs-on: ubunutu-latest
    needs: terraform
    permissions:
      id-token: write
      contents: read
    env:
      INVOKEURL: ${{needs.terraform.outputs.invoke_url}}
      S3DOMAIN: ${{needs.terraform.outputs.s3_domain}}
    defaults:
      run:
        working-directory: src/
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::784714698706:role/TEMP-GH-ACTIONS
          role-session-name: deploy-to-aws
          aws-region: us-east-2
      - name: Update js URL
        id: js-api_url
        run: sed -i -e 's/PLACEHOLDER/${{ env.INVOKEURL }}/' js/counter.js
      - name: Upload site to s3
        id: upload-to-s3
        run: |
          aws s3 sync ./ s3://${{env.S3DOMAIN}} --delete --follow-symlinks

