name: Destroy PR Environment

on:
    pull_request:
      types: [closed]

jobs:
  destroy_pr_env:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: terraform/
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::784714698706:role/github-actions-kyle.mn
          role-session-name: deploy-to-aws
          aws-region: us-east-2
      - name: Set Branch Name
        run: |
            echo "GH_BRANCH_NAME=${{github.head_ref}}" >> "$GITHUB_ENV"
      - uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Set terraform workspace
        id: tf-workspace
        run: terraform workspace select "${{env.GH_BRANCH_NAME}}-staging"

      - name: Destroy resources
        run: terraform destroy -auto-approve -var-file="staging.tfvars"
        
      - name: delete TF Workspace
        run: |
          terraform workspace select default
          terraform workspace delete "${{env.GH_BRANCH_NAME}}-staging"